# Generated by Django 6.0.3 on 2026-03-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='publicado', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default='servicios/default.jpg', upload_to='servicios/'),
            preserve_default=False,
        ),
    ]
