# Generated by Django 6.0.2 on 2026-03-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_estado_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='publicado', max_length=15),
        ),
    ]
