# Generated by Django 6.0.2 on 2026-03-22 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_estado'),
        ('usuarios', '0002_alter_perfilprofesional_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='servicios.servicio')),
            ],
        ),
    ]
