# Generated by Django 6.0.2 on 2026-03-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_aplicacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
