# Generated by Django 6.0.2 on 2026-03-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_visitadiagnostico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitadiagnostico',
            old_name='fecha',
            new_name='fecha_propuesta',
        ),
        migrations.AddField(
            model_name='visitadiagnostico',
            name='fecha_confirmada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitadiagnostico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('reprogramar', 'Reprogramar')], default='pendiente', max_length=20),
        ),
    ]
