# Generated by Django 6.0.2 on 2026-03-25 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_visitadiagnostico_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitadiagnostico',
            name='fecha_confirmada',
        ),
        migrations.RemoveField(
            model_name='visitadiagnostico',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='visitadiagnostico',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitadiagnostico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitadiagnostico',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
