# Generated by Django 6.0.2 on 2026-03-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_remove_visitadiagnostico_fecha_confirmada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
