# Generated by Django 6.0.2 on 2026-03-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional')], default='cliente', max_length=20, verbose_name='Tipo de usuario')),
                ('estado_cuenta', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de cuenta')),
                ('activo', models.BooleanField(default=False, verbose_name='Cuenta activada')),
                ('token_activacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de activación')),
                ('token_recuperacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de recuperación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('pintura', 'Pintura'), ('carpinteria', 'Carpintería'), ('albanileria', 'Albañilería'), ('jardineria', 'Jardinería'), ('limpieza', 'Limpieza del hogar'), ('cerrajeria', 'Cerrajería'), ('refrigeracion', 'Refrigeración y aire acondicionado'), ('instalaciones', 'Instalaciones en general'), ('otro', 'Otro')], max_length=50, verbose_name='Servicio que brinda')),
                ('servicio_descripcion', models.TextField(help_text='Describe con detalle el servicio que ofreces.', verbose_name='Descripción del servicio')),
                ('anos_experiencia', models.PositiveIntegerField(verbose_name='Años de experiencia')),
                ('historial', models.TextField(help_text='Describe tu experiencia, empleos anteriores, proyectos o logros relevantes.', verbose_name='Historial profesional')),
                ('certificaciones', models.TextField(blank=True, help_text='Opcional: menciona cursos, certificaciones o títulos relacionados.', null=True, verbose_name='Certificaciones o estudios')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro del perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil profesional',
                'verbose_name_plural': 'Perfiles profesionales',
                'db_table': 'perfiles_profesionales',
            },
        ),
    ]
