# Generated by Django 6.0.3 on 2026-03-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofesional',
            name='servicio',
            field=models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('pintura', 'Pintura'), ('albanileria', 'Albañilería'), ('limpieza', 'Limpieza del hogar'), ('otro', 'Otro')], max_length=50, verbose_name='Servicio que brinda'),
        ),
    ]
