# Generated by Django 4.2 on 2026-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilprofesional_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional'), ('admin', 'Administrador')], default='cliente', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
