# Generated by Django 4.2 on 2026-03-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('usuarios', 'Reporte de usuarios'), ('profesionales', 'Reporte de profesionales'), ('pendientes', 'Cuentas pendientes'), ('general', 'Reporte general')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_admin', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'reportes_admin',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
